### ISSUE TITLE
Add ability to set values for infinite numbers for dates and timestamps

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/spark-data-standardization#61]
## Background
Mainframes have various ways of representing dates. 

As the result we need to have assign special values to minimum and maximum dates, and also be able to specify these minimum and maximum dates.

## Feature
Add a new pattern, for mainframe dates.

## Example

```hocon
metadata {
  "pattern": "yyyyMMdd",
  "minus_infinity_symbol": "0",
  "minus_infinity_value": "10000101",
  "plus_infinity_symbol": "99999",
  "plus_infinity_value":  "99991231"
}
```

## Proposed Solution [Optional]
All new metadata keys are optional:
- `minus_infinity_symbol` - not used if not specified
- `minus_infinity_value` - a fixed default value is used
- `plus_infinity_symbol`- not used if not specified
- `plus_infinity_value`  - a fixed default value is used

Default values for minimum and maximum dates and timestamps can be used form here:
https://github.com/apache/spark/blob/070461cc673c3fc910e66d1cbf628632b558b48c/sql/core/src/main/scala/org/apache/spark/sql/jdbc/PostgresDialect.scala#L323

**Comment by benedeki** [comment]
If easy enough, please consider adding this ability to numbers too, so it doesn't have to be done in separate PR.
