### ISSUE TITLE
Existing config passing where possible

### ISSUE THREAD

**Issue by dk1844** [AbsaOSS/spark-data-standardization#8]
We have Typesafe config-based configuration that is usually loaded via `ConfigFactory.load()`. We also have a `ConfigReader` with enhancements and the ability to pass existing config, and we mix and match these approaches.

In this regard, it may be good time to revisit the usage of both and consider using a common approach -- this may also simplify testing to be able to pass an existing config as needed.

**Comment by Zejnilovic** [comment]
We changed how we generate config. Now they are case classes, still we should make the usability and passing of the config better, more natural.

**Comment by Zejnilovic** [comment]
Also make defaults int Config case class
